### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by 75lb** [75lb/object-tools#1]
- [ ] .extend() might need options - `clone` and `max-depth`
- [ ] .extend should only recurse into a plain object, not class instance (date, stream etc)
- [ ] when using .extend() on an array, an array should be returned, not an object
